services:
  app:
    container_name: app
    depends_on:
      - browserless
    build: .
    ports:
      - 3000:3000
    environment:
      - BROWSER_ENDPOINT=browserless:3000
      - TOKEN=S3CR3TL0V3RS

  browserless:
    container_name: browserless
    image: ghcr.io/browserless/chromium:latest@sha256:15042b7dfe5d60568d3ca5076cf90892125fdec6a54fd6034eb1cb3f717ca790
    ports:
      - 3001:3000
    environment:
      - TOKEN=S3CR3TL0V3RS
