[dev]
framework = "astro"
command = "yarn dev"
autoLaunch = false

[build]
command = "yarn build"
publish = "dist"
functions = "functions"

[functions]
external_node_modules = ["chrome-aws-lambda"]

[[redirects]]
from = "/image/*"
to = "/.netlify/functions/screenshot/:splat"
status = 200
force = true

[[plugins]]
package = "netlify-plugin-minify-html"

[plugins.inputs.minifierOptions]
collapseWhitespace = true
minifyJS = true
processScripts = ["module"]
