[dev]
autoLaunch = false

[build]
functions = "functions"

[functions]
external_node_modules = ["chrome-aws-lambda"]

[[redirects]]
from = "/image/*"
to="/.netlify/functions/screenshot/:splat"
status=200
force=true