[dev]
  framework = "astro"
  command = "pnpm run dev"
  autoLaunch = false

[build]
  command = "pnpm run build"
  publish = "dist"
  functions = "functions"

[functions]
  external_node_modules = ["chrome-aws-lambda"] 

[[redirects]]
  from = "/generate"
  to = "/image/:w/:h/:url"
  query = { w = ":w", h = ":h", url = ":url" }
  status = 301
  force = true

[[redirects]]
  from = "/image/:w/:h/:url"
  to = "/.netlify/functions/screenshot"
  status = 200
