[dev]
autoLaunch = false

[build]
command = "AWS_LAMBDA_FUNCTION_NAME=trickpuppeteer"
functions = "functions"

[functions]
external_node_modules = ["@sparticuz/chrome-aws-lambda"]

[[redirects]]
from = "/image/*"
to="/.netlify/functions/screenshot/:splat"
status=200
force=true