[dev]
  framework = "astro"
  command = "pnpm run dev"
  autoLaunch = false

[build]
  command = "pnpm run build"
  publish = "dist"
  functions = "functions"

[functions]
  external_node_modules = ["chrome-aws-lambda"] 

[[plugins]]
  package = "netlify-plugin-minify-html"

[plugins.inputs.minifierOptions]
  collapseWhitespace = true
  minifyJS = true
  processScripts = ["module"]

[[redirects]]
  from = "/img"
  to = "/image/:url"
  query = { url = ":url" }
  status = 301
  force = true

[[redirects]]
  from = "/img"
  to = "/image/:w/:h/:url"
  query = { w = ":w", h = ":h", url = ":url" }
  status = 301
  force = true

[[redirects]]
  from = "/image/*"
  to = "/.netlify/functions/screenshot/:splat"
  status = 200
  force = true
