[dev]
  autoLaunch = false

[build]
  command = "echo \"Building functions...\""
  functions = "src"

[[redirects]]
  from = "/"
  to = "/generate/:w/:h/:url"
  query = {url = ":url", w = ":w", h = ":h"}
  status = 301
  force = true

[[redirects]]
  from = "/"
  to = "/generate/:url"
  query = {url = ":url"}
  status = 301
  force = true

[[redirects]]
  from = "/generate/*"
  to = "/.netlify/builders/api/:splat"
  status = 200

[[redirects]]
  from = "/"
  to = "/.netlify/builders/start/:splat"
  status = 200