#:schema node_modules/wrangler/config-schema.json
name = "screenshot"
main = "src/worker.ts"
compatibility_date = "2024-07-12"
compatibility_flags = ["nodejs_compat"]


browser = { binding = "BROWSER" }
[[kv_namespaces]]
binding = "BROWSER_KV_DEMO"
id = "4902b202285840cb987c7aba1bc40bf7"
preview_id = "8662a5e215434dd5bd94b83053bd8a59"
