name: 'Deploy to Server'

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: dokku/github-action@master
        with:
          git_remote_url: 'ssh://dokku@ss.sngr.xyz:22/app'
          ssh_private_key: ${{ secrets.DOKKU_SSH_KEY }}
          branch: main
